// <auto-generated />
namespace PetPickr.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Tuesdayfourthmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tuesdayfourthmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202105181705581_Tuesday fourth migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
