// <auto-generated />
namespace PetPickr.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class wednesdayafternoonmigTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wednesdayafternoonmigTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "202105261846481_wednesday afternoon migTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
